# Generated by Django 3.1.1 on 2020-10-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host_name', models.CharField(max_length=64)),
                ('service_name', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=16)),
                ('sent_at', models.DateTimeField()),
            ],
            options={
                'unique_together': {('host_name', 'service_name')},
            },
        ),
    ]
