# Generated by Django 3.1.1 on 2020-10-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_serviceacknowledgement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDowntime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('host_name', models.CharField(max_length=64)),
                ('info', models.CharField(default='', max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('started_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('host_name', 'name')},
            },
        ),
    ]
