"""
Django settings for nogios project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ezud@c2m&x!p4kfr*w#wd962*@sh5)+!v^$4((*c!(e8odfx2r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_mysql',
    'rest_framework',
    'corsheaders',
    'django_crontab',
    'apps.helpers',
    'apps.hosts',
    'apps.contacts',
    'apps.services',
    'apps.commands',
    'apps.time_periods',
    'apps.status',
    'apps.runners',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nogios.urls'

CORS_ORIGIN_WHITELIST = (
    'http://localhost:8080',
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nogios.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'HOST':     '127.0.0.1',
#         'PORT':     '3306',
#         'NAME':     'nogios',
#         'USER':     'nogios',
#         'PASSWORD': 'nogios',
#         'OPTIONS': {
#             'charset':  'utf8mb4',
#         }
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME':   'dev_db.sqlite'
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'nogios-in-memory',
        'TIMEOUT': 3600,
        'OPTIONS': {
            'MAX_ENTRIES': 5000
        }
    }
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
BASE_URL = 'http://localhost:8000'
CONFIG_BASE_PATH = BASE_DIR / 'conf.d.example'
DEFAULT_LOCATION = 'dc-1'
DEFAULT_RETRY_ATTEMPTS = 4
DEFAULT_RETRY_INTERVAL = 1
DEFAULT_CHECK_INTERVAL = 15
DEFAULT_NOTIFICATION_INTERVAL = 15
DEFAULT_CHECK_CHANNEL = 'Ssh'  # Ssh|Udp|Tcp|Nrpe|CheckNrpe|LocalShell

CHECK_NRPE_PATH = '/urs/bin/check_nrpe'
SSL_CIPHER_FILTER = 'ALL:!DES:!RC4:!MD5:!PSK:!LOW:@SECLEVEL=0'
NRPE_PACKET_VERSION = 2

ALLOWED_CLIENT_SUBNETS = [
    '127.0.0.1/32',
]

USE_NOTIFICATIONS_QUEUE = False
NOTIFICATIONS_QUEUE_HOST = 'localhost'
NOTIFICATIONS_QUEUE_NAME = 'nogios'
NOTIFICATIONS_QUEUE_USER = 'rabbitmq'
NOTIFICATIONS_QUEUE_PASSWORD = 'rabbitmq'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_PORT = 25
EMAIL_FROM = 'Nogios <no-reply@nogios.net>'
EMAIL_HOST_USER = 'user'
EMAIL_HOST_PASSWORD = 'password'
EMAIL_USE_TLS = False
EMAIL_USE_SSL = False

JIRA_ENDPOINT = 'https://jira.example.com'
JIRA_USER_NAME = 'rest-api-user'
JIRA_USER_PASSWORD = 'rest-api-password'
JIRA_TRIGGERING_STATUS = 'CRITICAL'
JIRA_PRIORITY = 'Critical'
JIRA_TRANSITION_RESOLVED_ID = '511'
JIRA_RESOLUTION_ID = '0'
JIRA_POST_COMMENTS = False
JIRA_CLOSE_WHEN_RESTORE = True
JIRA_ISSUE_TYPE = 'Task'
JIRA_TYPE_OK = 'OK'

SSH_KEY_PATH = 'path to id_rsa'
SSH_KEY_PASS_PHRASE = None
SSH_KNOWN_HOSTS = 'path to known_hosts'

CRONJOBS = [
    ('* * * * *', 'apps.runners.cron.run_checks', '>> /tmp/nogios_scheduled_job.log')
]

FAILURE_STATUSES = [
    'UNKNOWN',
    'WARNING',
    'CRITICAL',
    'BLOCKER',
    'DOWN',
]
