# Generated by Django 3.1.3 on 2020-11-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_periods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeperiodconfig',
            name='config',
            field=models.JSONField(max_length=4096),
        ),
    ]
