# Generated by Django 3.1.1 on 2020-10-13 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host_name', models.CharField(max_length=64, unique=True)),
                ('address', models.CharField(max_length=64, unique=True)),
                ('location', models.CharField(max_length=64)),
                ('config', models.JSONField(max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostStatus',
            fields=[
                ('name', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('alias', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HostToRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host_name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('address', models.CharField(max_length=64, unique=True)),
                ('output', models.CharField(max_length=2048)),
                ('attempts', models.SmallIntegerField(default=0)),
                ('hard_status', models.BooleanField(db_index=True, default=False)),
                ('executed_at', models.DateTimeField(auto_now=True)),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hosts.hoststatus')),
            ],
            options={
                'ordering': ['host_name'],
            },
        ),
    ]
